# Configuration for notcurses 3.0.11+
[env]
PKG_CONFIG_PATH = "/usr/local/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig"
LD_LIBRARY_PATH = "/usr/local/lib:/usr/lib/x86_64-linux-gnu"

[build]
rustflags = ["-L", "/usr/local/lib", "-l", "notcurses", "-l", "notcurses-core"]
