[package]
name = "tui-framework-macros"
version = "0.1.0"
edition = "2021"
description = "Procedural macros for the TUI framework"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
